### ISSUE TITLE
average_steer_partitions.py improvement suggestions

### ISSUE THREAD

**Issue by ChristofDubs** [donadigo/gbxtools#8]
Hi, I have looked a bit through the `average_steer_partitions.py` script, and have thought of some suggestions for improvements:

- rather than partitioning the data (which ignores changes across the boundary of two partitions, and the max spikes per seconds depends on where the partitions are made), it would be better to identify the spikes first, and then use a sliding window instead.
-  rather than comparing difference between two consecutive inputs, compare the differences between consecutive extrema (local minima and maxima). This is less sensitive to the exact shape of the input.
- Rather than using time windows, it might make more sense to use a "spike window" (i.e. how far apart in time are `N` spikes, rather than how many spikes are there in `delta_t` time)
-  On another note, what does this obscure looking code [here](https://github.com/donadigo/gbxtools/blob/master/average_steer_partitions.py#L33) do?
    ```python
    if etime % 10 == 5:
         etime -= 65535
    ```

Unfortunately, I could run it on actual data as I couldn't run your scripts due to failing to install the dependencies properly (`pip3 install pygbx` failed because `pip3 install python-lzo` failed).

Regarding the first two improvement points, I put together a the following sample script: 

```python

import numpy as np
import matplotlib.pyplot as plt


def getExtrema(data):
    # find extrema
    extrema_pts = []

    for i in range(1, len(data) - 1):
        if data[i - 1][1] < data[i][1] >= data[i + 1][1] or data[i - 1][1] > data[i][1] <= data[i + 1][1]:
            extrema_pts.append(data[i])

    return extrema_pts


def filterExtrema(extrema_pts, diff_threshold):
    # filter out extrema points with difference < diff_threshold

    if len(extrema_pts) == 0:
        return []

    filtered_pts = [extrema_pts[0]]
    for i in range(1, len(extrema_pts)):
        if (np.abs(extrema_pts[i][1] - extrema_pts[i - 1][1]) > diff_threshold):
            filtered_pts.append(extrema_pts[i])

    return filtered_pts


def getSpikesPerSec(filtered_pts, window_size):
    # calculating spikes per sec over a sliding window

    num_pts_per_sec = []
    i = j = 0
    while True:
        while i < len(filtered_pts) - 1 and filtered_pts[i][0] <= filtered_pts[j][0] + window_size:
            i += 1

        num_pts_per_sec.append([filtered_pts[j][0], (i + 1 - j) / (filtered_pts[i][0] - filtered_pts[j][0])])
        if i >= len(filtered_pts) - 1:
            return num_pts_per_sec

        j += 1


# parameter
THRESHOLD = 10000
FILTER_TIME_WINDOW = 1.3

# generate sample signal
N = 1000
T = 1.0 / 100.0

t = np.linspace(0.0, N * T, N, endpoint=False)

x = 10000 * np.sin(1 * 2.0 * np.pi * t) + 12000 * np.sin(1.7 * 2.0 * np.pi * t) + 5000 * np.sin(2.9 * 2.0 * np.pi * t)

x[100:150] = np.ones(50)
x[300:350] = np.ones(50)

plt.figure()
plt.plot(t, x, label='steering signal')
plt.xlabel('time [s]')

# convert to list of [timestamp, data]
data = [[t[i], x[i]] for i in range(len(t))]

extrema_pts = getExtrema(data)
filtered_pts = filterExtrema(extrema_pts, THRESHOLD)

plt.plot([p[0] for p in extrema_pts], [p[1] for p in extrema_pts], 'g*', label='extrema')
plt.plot([p[0] for p in filtered_pts], [p[1] for p in filtered_pts], 'r*', label='filtered extrema (threshold: {})'.format(THRESHOLD))
plt.legend()

num_pts_per_sec = getSpikesPerSec(filtered_pts, FILTER_TIME_WINDOW)

print('total number of spikes: {}'.format(len(filtered_pts)))
if len(data) > 1:
    print('average of number of spikes per sec: {}'.format(len(filtered_pts) * 1.0 / (data[-1][0] - data[0][0])))
if len(num_pts_per_sec) > 0:
    print('max number of Spikes per sec: {}'.format(max([p[1] for p in num_pts_per_sec])))

plt.figure()
plt.plot([p[0] for p in num_pts_per_sec], [p[1] for p in num_pts_per_sec])
plt.xlabel('time [s]')
plt.ylabel('Spikes per second [-]')
plt.title('Spikes per second (using filter window of {} sec)'.format(FILTER_TIME_WINDOW))
plt.show()
```

Output:
![Figure_1-6](https://user-images.githubusercontent.com/4960007/120920515-2502db80-c6fa-11eb-9206-94634e8c2cc4.png)
![Figure_2](https://user-images.githubusercontent.com/4960007/120920520-28966280-c6fa-11eb-921f-69f3d820fde3.png)

Feel free to ask for clarifications, and let me know your thoughts.

**Comment by R00dRallec** [comment]
Hey mate,

You can install python-lzo 'pre-compiled' as python weehl package using pip. I did it the same way on my machine: https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-lzo

See https://stackoverflow.com/a/28002930/5653685 for installation of wheel files.

**Comment by ChristofDubs** [comment]
> Hey mate,
> 
> You can install python-lzo 'pre-compiled' as python weehl package using pip. I did it the same way on my machine: https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-lzo
> 
> See https://stackoverflow.com/a/28002930/5653685 for installation of wheel files.

Thanks for the help. This didn't work on ubuntu, but after a bit more reading, `pip3 install python-lzo` was successful after `sudo apt-get install zlib1g-dev liblzo2-dev`
